---
- id: 'pyspelling'
  name: 'pyspelling'
  language: 'python'
  entry: 'pyspelling'
  types:
    - 'markdown'
  pass_filenames: true
  verbose: true
#  additional_dependencies:
#    - 'pyspelling'
#    - 'pymdown-extensions'
...
