---
name: 'yamllint'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  yamllint:
    name: 'yamllint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'yamllint'
        uses: 'karancode/yamllint-github-action@v2.1.1'
        with:
          yamllint_file_or_dir: './'
          yamllint_strict: true
          yamllint_comment: false
          yamllint_config_filepath: './yamllint'
...
